# Generated by Django 3.1.5 on 2021-02-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_resolve_app', '0006_auto_20210220_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
