# Generated by Django 3.1.5 on 2021-02-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error_resolve_app', '0007_article_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='path',
        ),
    ]
