# Generated by Django 3.1.5 on 2021-02-21 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('error_resolve_app', '0008_remove_article_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
