# Generated by Django 3.1.5 on 2021-02-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_resolve_app', '0009_article_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
